# Tensorflow 2.X

In [1]:
# !pip install tensorflow

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.2.0'

## Constants

### Creating a constant

In [4]:
#Creating a constant in TensorFlow 2.X
tensor = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [7]:
# Visualizing dimensions of tensor
tensor.shape

TensorShape([2, 2])

### Getting values of a constant

In [8]:
tensor.numpy()

array([[23,  4],
       [32, 51]])

In [15]:
#Convert a numpy array to tensor
numpy_tensor = np.array([[23,4], [32, 51]])

In [16]:
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

## Variables

### Creating a variable

In [12]:
tf_variable = tf.Variable([[1, 2, 3], [4, 5, 6]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### Getting values of a variable

In [13]:
tf_variable.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

### Updating a specific value in a variable

In [14]:
tf_variable[0, 2].assign(100)
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[  1,   2, 100],
       [  4,   5,   6]])>

## Operation with tensors

In [18]:
tensor = tf.constant([[1,2], [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### Addition tensor with scalar

In [19]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

### Multiplication tensor with scalar

In [20]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

### Using numpy functions to operate tensors

In [21]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [22]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [23]:
np.dot(tensor, tensor)

array([[ 7, 10],
       [15, 22]])

## Strings

In [25]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

### Simple operations with string

In [26]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [27]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119])>

### Storing string array

In [28]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [34]:
#Iterating through the TF string array
for string in tf_string_array:
    print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
